# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: carolinak
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: cd
service: shui-board

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:
    esbuild:
    minify: true

    package:
  individually: true

functions:
  createMessage:
    handler: functions/createMessage/index.handler
    events:
      - httpApi:
          path: /messages
          method: post
          cors: true

  listMessages:
    handler: functions/listMessages/index.handler
    events:
      - httpApi:
          path: /messages
          method: get
          cors: true

  updateMessage:
    handler: functions/updateMessage/index.handler
    events:
      - httpApi:
          path: /messages/{id}
          method: put
          cors: true

  resources:
  Resources:
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ShuiMessages
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: messageId
            AttributeType: S
          - AttributeName: username
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: messageId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userIndex
            KeySchema:
              - AttributeName: username
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
