org: carolinak
app: cd
service: shui-board

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: arn:aws:iam::298156079429:role/carolinas-shui-board-role

package:
  individually: true

build:
  esbuild:
    minify: true

functions:
  createMessage:
    handler: functions/createMessage/index.handler
    events:
      - httpApi:
          path: /messages
          method: post

  listMessages:
    handler: functions/listMessages/index.handler
    events:
      - httpApi:
          path: /messages
          method: get

  updateMessage:
    handler: functions/updateMessage/index.handler
    events:
      - httpApi:
          path: /messages/{id}
          method: put

resources:
  Resources:
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ShuiMessages
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: messageId
            AttributeType: S
          - AttributeName: username
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: messageId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userIndex
            KeySchema:
              - AttributeName: username
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
